In [1]:
import sys
sys.path.append('..')

import torch
from torch import nn
from src.model import InputEmbeddings, PositionalEncoding, LayerNormalization
import numpy as np

In [26]:
d_model = 512
n = 9
vocab_size = 10000
max_seq_len = 256
dropout = 0
batch_size = 32

In [30]:
x = np.random.randint(0, vocab_size, (batch_size, n))
x = torch.tensor(x, dtype=torch.long)
print(x.shape)


torch.Size([32, 9])


In [31]:
input_embeddings = InputEmbeddings(d_model, vocab_size)
positional_encoding = PositionalEncoding(d_model, max_seq_len, dropout)

In [32]:
x = input_embeddings(x)
x.shape

torch.Size([32, 9, 512])

In [33]:
x

tensor([[[ -3.8993,  -5.8090,   6.4034,  ...,   3.4399,   6.9648,  21.7009],
         [  6.7543, -10.4421, -38.3409,  ...,  -0.2369,  -7.1562,   7.3068],
         [ 35.1011, -40.9905, -10.8354,  ..., -12.8708,  22.8944,  -8.4337],
         ...,
         [  8.7058, -15.2709,  31.5261,  ..., -51.8829, -39.9597, -10.4008],
         [ -3.8711,  14.1379, -11.0966,  ...,  -0.6986, -24.5576,  -0.5017],
         [ 26.0834, -42.2604,  13.8897,  ..., -60.5199,  -4.7102,  18.9656]],

        [[-10.4016,  17.9354, -18.6063,  ...,  37.9845,   3.6093, -31.8059],
         [ -8.7725,   4.3487,  44.5939,  ...,  19.7421, -10.9009,  21.0799],
         [-11.2130, -13.7007,  11.8039,  ...,  23.3890,  -5.5408, -20.9183],
         ...,
         [ 16.7499,   7.5750,  14.9543,  ...,  11.7086,  65.2691, -48.7340],
         [ 14.6518,   2.6589,  -9.2543,  ...,  30.0831,   7.2107,   3.4707],
         [-28.6187,   9.4217,  31.0871,  ...,  -8.8870,   5.8565, -11.2194]],

        [[ -2.6316,  19.3713, -21.8276,  ...

In [34]:
x[0, 1, 0]

tensor(6.7543, grad_fn=<SelectBackward0>)

In [35]:
x = positional_encoding(x)
x.shape


torch.Size([32, 9, 512])

In [36]:
x

tensor([[[ -3.8993,  -4.8090,   6.4034,  ...,   4.4399,   6.9648,  22.7009],
         [  7.5958,  -9.9018, -37.5191,  ...,   0.7631,  -7.1561,   8.3068],
         [ 36.0104, -41.4067,  -9.8990,  ..., -11.8708,  22.8946,  -7.4337],
         ...,
         [  8.4264, -14.3107,  31.0509,  ..., -50.8829, -39.9591,  -9.4008],
         [ -3.2141,  14.8918, -10.6442,  ...,   0.3014, -24.5569,   0.4983],
         [ 27.0727, -42.4059,  14.8804,  ..., -59.5199,  -4.7094,  19.9656]],

        [[-10.4016,  18.9354, -18.6063,  ...,  38.9845,   3.6093, -30.8059],
         [ -7.9311,   4.8890,  45.4157,  ...,  20.7421, -10.9007,  22.0799],
         [-10.3037, -14.1168,  12.7403,  ...,  24.3890,  -5.5406, -19.9183],
         ...,
         [ 16.4705,   8.5351,  14.4791,  ...,  12.7086,  65.2697, -47.7340],
         [ 15.3088,   3.4128,  -8.8019,  ...,  31.0831,   7.2115,   4.4707],
         [-27.6293,   9.2762,  32.0777,  ...,  -7.8870,   5.8573, -10.2194]],

        [[ -2.6316,  20.3713, -21.8276,  ...

In [37]:
x[0, 1, 0]

tensor(7.5958, grad_fn=<SelectBackward0>)

In [38]:
positional_encoding.get_buffer('pe')[:, :n, :][0, 1, 0]

tensor(0.8415)

In [39]:
2.1798 + 8.4147e-01

3.0212700000000003

In [40]:
-34.0306 + positional_encoding.get_buffer('pe')[:, :n, :][0, 1, 0]

tensor(-33.1891)

In [41]:
layer_norm = LayerNormalization()

In [45]:
x

tensor([[[ -3.8993,  -4.8090,   6.4034,  ...,   4.4399,   6.9648,  22.7009],
         [  7.5958,  -9.9018, -37.5191,  ...,   0.7631,  -7.1561,   8.3068],
         [ 36.0104, -41.4067,  -9.8990,  ..., -11.8708,  22.8946,  -7.4337],
         ...,
         [  8.4264, -14.3107,  31.0509,  ..., -50.8829, -39.9591,  -9.4008],
         [ -3.2141,  14.8918, -10.6442,  ...,   0.3014, -24.5569,   0.4983],
         [ 27.0727, -42.4059,  14.8804,  ..., -59.5199,  -4.7094,  19.9656]],

        [[-10.4016,  18.9354, -18.6063,  ...,  38.9845,   3.6093, -30.8059],
         [ -7.9311,   4.8890,  45.4157,  ...,  20.7421, -10.9007,  22.0799],
         [-10.3037, -14.1168,  12.7403,  ...,  24.3890,  -5.5406, -19.9183],
         ...,
         [ 16.4705,   8.5351,  14.4791,  ...,  12.7086,  65.2697, -47.7340],
         [ 15.3088,   3.4128,  -8.8019,  ...,  31.0831,   7.2115,   4.4707],
         [-27.6293,   9.2762,  32.0777,  ...,  -7.8870,   5.8573, -10.2194]],

        [[ -2.6316,  20.3713, -21.8276,  ...

In [44]:
layer_norm(x)

tensor([[[-0.1913, -0.2320,  0.2696,  ...,  0.1818,  0.2947,  0.9986],
         [ 0.3304, -0.4854, -1.7731,  ...,  0.0119, -0.3574,  0.3636],
         [ 1.6309, -1.8485, -0.4324,  ..., -0.5210,  1.0415, -0.3216],
         ...,
         [ 0.4410, -0.5585,  1.4355,  ..., -2.1662, -1.6860, -0.3427],
         [-0.1075,  0.6635, -0.4238,  ...,  0.0422, -1.0163,  0.0506],
         [ 1.1963, -1.8689,  0.6584,  ..., -2.6239, -0.2058,  0.8828]],

        [[-0.4998,  0.7883, -0.8601,  ...,  1.6686,  0.1153, -1.3958],
         [-0.3710,  0.1696,  1.8786,  ...,  0.8381, -0.4962,  0.8945],
         [-0.5159, -0.6897,  0.5342,  ...,  1.0650, -0.2989, -0.9540],
         ...,
         [ 0.6981,  0.3503,  0.6108,  ...,  0.5332,  2.8368, -2.1157],
         [ 0.6644,  0.1161, -0.4470,  ...,  1.3916,  0.2912,  0.1649],
         [-1.3208,  0.3514,  1.3846,  ..., -0.4263,  0.1965, -0.5320]],

        [[-0.0863,  0.9442, -0.9462,  ..., -1.0465,  1.6622,  2.7444],
         [ 1.1318,  0.5531, -0.8067,  ..., -0